
package proxy;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebService(name = "CreditCardController", targetNamespace = "http://controller.creditcardvalidatorsoap.hergal.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditCardController {


    /**
     * 
     * @param cardNumber
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isNumberCreditCardValide", targetNamespace = "http://controller.creditcardvalidatorsoap.hergal.com/", className = "proxy.IsNumberCreditCardValide")
    @ResponseWrapper(localName = "isNumberCreditCardValideResponse", targetNamespace = "http://controller.creditcardvalidatorsoap.hergal.com/", className = "proxy.IsNumberCreditCardValideResponse")
    @Action(input = "http://controller.creditcardvalidatorsoap.hergal.com/CreditCardController/isNumberCreditCardValideRequest", output = "http://controller.creditcardvalidatorsoap.hergal.com/CreditCardController/isNumberCreditCardValideResponse")
    public boolean isNumberCreditCardValide(
        @WebParam(name = "cardNumber", targetNamespace = "")
        String cardNumber);

}
