
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CreditCardWS", targetNamespace = "http://controller.creditcardvalidatorsoap.hergal.com/", wsdlLocation = "http://localhost:8182/?wsdl")
public class CreditCardWS
    extends Service
{

    private static final URL CREDITCARDWS_WSDL_LOCATION;
    private static final WebServiceException CREDITCARDWS_EXCEPTION;
    private static final QName CREDITCARDWS_QNAME = new QName("http://controller.creditcardvalidatorsoap.hergal.com/", "CreditCardWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8182/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CREDITCARDWS_WSDL_LOCATION = url;
        CREDITCARDWS_EXCEPTION = e;
    }

    public CreditCardWS() {
        super(__getWsdlLocation(), CREDITCARDWS_QNAME);
    }

    public CreditCardWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), CREDITCARDWS_QNAME, features);
    }

    public CreditCardWS(URL wsdlLocation) {
        super(wsdlLocation, CREDITCARDWS_QNAME);
    }

    public CreditCardWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CREDITCARDWS_QNAME, features);
    }

    public CreditCardWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreditCardWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CreditCardController
     */
    @WebEndpoint(name = "CreditCardControllerPort")
    public CreditCardController getCreditCardControllerPort() {
        return super.getPort(new QName("http://controller.creditcardvalidatorsoap.hergal.com/", "CreditCardControllerPort"), CreditCardController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CreditCardController
     */
    @WebEndpoint(name = "CreditCardControllerPort")
    public CreditCardController getCreditCardControllerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://controller.creditcardvalidatorsoap.hergal.com/", "CreditCardControllerPort"), CreditCardController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CREDITCARDWS_EXCEPTION!= null) {
            throw CREDITCARDWS_EXCEPTION;
        }
        return CREDITCARDWS_WSDL_LOCATION;
    }

}
